### ISSUE TITLE
upload hello world program in your favorite langauge

### ISSUE THREAD

**Issue by rahulsain** [rahulsain3000/hello-world#2]
any hello world program from any language are accepted but must be a valid program

**Comment by naman-150200** [comment]
i would like to solve this issue

**Comment by rahulsain** [comment]
> i would like to solve this issue

sure

**Comment by poojapatil010677** [comment]
I would like to contribute

**Comment by rahulsain** [comment]
> I would like to contribute

sure

**Comment by rajsinghparihar** [comment]
I'd like to contribute.

**Comment by jilloestreicher** [comment]
I would like to contribute

**Comment by Suvid-Singhal** [comment]
Can I contribute to this repo for hacktoberfest?

**Comment by dyominov** [comment]
I would like to contribute

**Comment by Suvid-Singhal** [comment]
Can i do this during hacktoberfest @rahulsain3000 ?? Will it count as a PR?

**Comment by rahulsain** [comment]
It will count as a valid PR if you make a PR in October not now

It must have a valid code in the language that is not yet in this repo. 

Hope I clear all your doubts.

**Comment by erwinkaaa** [comment]
I would like to contribute

**Comment by Priyanshu2802** [comment]
I would love to contribute during HACKTOBERFEST

**Comment by rahulsain** [comment]
Sure @Priyanshu2802  everyone is welcome!

**Comment by Shagufta08** [comment]
I would like to contribute.

**Comment by apekshamanchanda** [comment]
I would like to contribute too
