### ISSUE TITLE
need attention

### ISSUE THREAD

**Issue by rahulsain** [rahulsain3000/hello-world#42]
update hello wolrd

**Comment by kalpanaT-05** [comment]
hey @rahulsain3000 i can contribute in this project, iff you assign me
thank you so much in advanced :)

**Comment by rahulsain** [comment]
sure @kalpanaT-05

**Comment by kalpanaT-05** [comment]
> sure @kalpanaT-05

thank you so much, I'll add the file and update you accordingly

**Comment by kalpanaT-05** [comment]
hey @rahulsain3000 i've created PR please check it and merge it
thank you
